# Generated by Django 3.2.5 on 2021-09-21 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarketapp', '0002_remove_supermarketmodel_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermarketmodel',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarketapp.items'),
        ),
    ]
