# Generated by Django 3.2.5 on 2021-09-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarketapp', '0003_supermarketmodel_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_mobile', models.CharField(max_length=10)),
                ('customer_address', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField(null=True)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.FloatField()),
            ],
        ),
    ]
